services:
    redis-server:
        image: docker.io/redis
        volumes:
            - ./redis:/data
        command: ["redis-server", "--save", "--protected-mode", "no"]
    node-app:
        build: ./
        image: docker.io/supraja017/visits
        ports:
            - "8081:8081"